package com.redhat.saude.cotadorsaude.responses;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TabelaPrecoResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Faixa Etaria")
	private com.redhat.saude.cotadorsaude.FaixaEtaria faixaEtaria;
	@org.kie.api.definition.type.Label(value = "Planos")
	private java.util.List<com.redhat.saude.cotadorsaude.Plano> planos;

	public TabelaPrecoResponse() {
	    planos = new java.util.ArrayList();
	}

	public com.redhat.saude.cotadorsaude.FaixaEtaria getFaixaEtaria() {
		return this.faixaEtaria;
	}

	public void setFaixaEtaria(
			com.redhat.saude.cotadorsaude.FaixaEtaria faixaEtaria) {
		this.faixaEtaria = faixaEtaria;
	}

	public java.util.List<com.redhat.saude.cotadorsaude.Plano> getPlanos() {
		return this.planos;
	}

	public void setPlanos(
			java.util.List<com.redhat.saude.cotadorsaude.Plano> planos) {
		this.planos = planos;
	}

	public TabelaPrecoResponse(
			com.redhat.saude.cotadorsaude.FaixaEtaria faixaEtaria,
			java.util.List<com.redhat.saude.cotadorsaude.Plano> planos) {
		this.faixaEtaria = faixaEtaria;
		this.planos = planos;
	}

}