package com.redhat.saude.cotadorsaude.requests;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ListarPremiosPorPlanoRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Código da região")
	private java.lang.Integer regiao;
	@org.kie.api.definition.type.Label(value = "código do produto")
	private java.lang.Integer produto;
	@org.kie.api.definition.type.Label(value = "Nome do Plano")
	private java.lang.String plano;

	public ListarPremiosPorPlanoRequest() {
	}

	public java.lang.Integer getRegiao() {
		return this.regiao;
	}

	public void setRegiao(java.lang.Integer regiao) {
		this.regiao = regiao;
	}

	public java.lang.Integer getProduto() {
		return this.produto;
	}

	public void setProduto(java.lang.Integer produto) {
		this.produto = produto;
	}

	public java.lang.String getPlano() {
		return this.plano;
	}

	public void setPlano(java.lang.String plano) {
		this.plano = plano;
	}

	public ListarPremiosPorPlanoRequest(java.lang.Integer regiao,
			java.lang.Integer produto, java.lang.String plano) {
		this.regiao = regiao;
		this.produto = produto;
		this.plano = plano;
	}

}