package com.redhat.saude.cotadorsaude;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Adesao implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Faixa Etária")
	private com.redhat.saude.cotadorsaude.FaixaEtaria faixaEtaria;
	@org.kie.api.definition.type.Label(value = "Quantidade de Vidas")
	private java.lang.Integer qtdVidas;

	public Adesao() {
	}

	public com.redhat.saude.cotadorsaude.FaixaEtaria getFaixaEtaria() {
		return this.faixaEtaria;
	}

	public void setFaixaEtaria(
			com.redhat.saude.cotadorsaude.FaixaEtaria faixaEtaria) {
		this.faixaEtaria = faixaEtaria;
	}

	public java.lang.Integer getQtdVidas() {
		return this.qtdVidas;
	}

	public void setQtdVidas(java.lang.Integer qtdVidas) {
		this.qtdVidas = qtdVidas;
	}

	public Adesao(com.redhat.saude.cotadorsaude.FaixaEtaria faixaEtaria,
			java.lang.Integer qtdVidas) {
		this.faixaEtaria = faixaEtaria;
		this.qtdVidas = qtdVidas;
	}

}