package com.redhat.saude.cotadorsaude;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CalcularPremioRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Região")
	private java.lang.Integer regiao;
	@org.kie.api.definition.type.Label("Produto")
	private java.lang.Integer produto;
	@org.kie.api.definition.type.Label("Plano")
	private java.lang.String plano;

	@org.kie.api.definition.type.Label(value = "Adesões")
	private java.util.List<com.redhat.saude.cotadorsaude.Adesao> adesoes;

	public CalcularPremioRequest() {
	}

    public com.redhat.saude.cotadorsaude.Adesao retornarAdesaoPorFaixaEtaria(int faixaInicial,int faixaFinal){
        for(com.redhat.saude.cotadorsaude.Adesao adesao: adesoes){
            com.redhat.saude.cotadorsaude.FaixaEtaria faixa = adesao.getFaixaEtaria();
            if (faixa.getInicio() == faixaInicial && faixa.getFim() == faixaFinal){
                return adesao;
            }
        }
        return null;
    }

	public java.lang.Integer getRegiao() {
		return this.regiao;
	}

	public void setRegiao(java.lang.Integer regiao) {
		this.regiao = regiao;
	}

	public java.lang.Integer getProduto() {
		return this.produto;
	}

	public void setProduto(java.lang.Integer produto) {
		this.produto = produto;
	}

	public java.lang.String getPlano() {
		return this.plano;
	}

	public void setPlano(java.lang.String plano) {
		this.plano = plano;
	}

	public java.util.List<com.redhat.saude.cotadorsaude.Adesao> getAdesoes() {
		return this.adesoes;
	}

	public void setAdesoes(
			java.util.List<com.redhat.saude.cotadorsaude.Adesao> adesoes) {
		this.adesoes = adesoes;
	}

	public CalcularPremioRequest(java.lang.Integer regiao,
			java.lang.Integer produto, java.lang.String plano,
			java.util.List<com.redhat.saude.cotadorsaude.Adesao> adesoes) {
		this.regiao = regiao;
		this.produto = produto;
		this.plano = plano;
		this.adesoes = adesoes;
	}

}