package com.redhat.saude.cotadorsaude;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CalcularPremioResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Premios")
	private java.util.List<com.redhat.saude.cotadorsaude.Premio> premios;

	public CalcularPremioResponse() {
	    premios = new java.util.ArrayList();
	}

	public java.util.List<com.redhat.saude.cotadorsaude.Premio> getPremios() {
		return this.premios;
	}

	public void setPremios(
			java.util.List<com.redhat.saude.cotadorsaude.Premio> premios) {
		this.premios = premios;
	}

	public CalcularPremioResponse(
			java.util.List<com.redhat.saude.cotadorsaude.Premio> premios) {
		this.premios = premios;
	}

}