package com.redhat.saude.cotadorsaude;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FaixaEtaria implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Inicio da faixa")
	private java.lang.Integer inicio;
	@org.kie.api.definition.type.Label(value = "Fim da faixa")
	private java.lang.Integer fim;

	public FaixaEtaria() {
	}

	public java.lang.Integer getInicio() {
		return this.inicio;
	}

	public void setInicio(java.lang.Integer inicio) {
		this.inicio = inicio;
	}

	public java.lang.Integer getFim() {
		return this.fim;
	}

	public void setFim(java.lang.Integer fim) {
		this.fim = fim;
	}

	public FaixaEtaria(java.lang.Integer inicio, java.lang.Integer fim) {
		this.inicio = inicio;
		this.fim = fim;
	}

}