package com.redhat.saude.cotadorsaude;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ListarPremiosPorPlanoResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Nome do Plano")
	private java.lang.String nomePlano;
	@org.kie.api.definition.type.Label("Valor de 0 a 18 anos")
	private java.lang.Double valorDe00a18;
	@org.kie.api.definition.type.Label("Valor de 19 a 23")
	private java.lang.Double valorDe19a23;
	@org.kie.api.definition.type.Label("Valor de 24 a 28")
	private java.lang.Double valorDe24a28;
	@org.kie.api.definition.type.Label("Valor de 29 a 33")
	private java.lang.Double valorDe29a33;
	@org.kie.api.definition.type.Label("Valor de 34 a 38")
	private java.lang.Double valorDe34a38;
	@org.kie.api.definition.type.Label("Valor de 39 a 43")
	private java.lang.Double valorDe39a43;
	@org.kie.api.definition.type.Label("Valor de 44 a 48")
	private java.lang.Double valorDe44a48;
	@org.kie.api.definition.type.Label("Valor de 49 a 53")
	private java.lang.Double valorDe49a53;
	@org.kie.api.definition.type.Label("Valor de 54 a 58")
	private java.lang.Double valorDe54a58;
	@org.kie.api.definition.type.Label("Valor a partir de 59")
	private java.lang.Double valorAPartir59;

	@org.kie.api.definition.type.Label(value = "Premios")
	private java.util.List<com.redhat.saude.cotadorsaude.Premio> premios = new java.util.ArrayList();

	public ListarPremiosPorPlanoResponse() {
	}

    public void configurePremios(){
        premios.add(new Premio(new com.redhat.saude.cotadorsaude.FaixaEtaria(0,18),valorDe00a18));
        premios.add(new Premio(new com.redhat.saude.cotadorsaude.FaixaEtaria(19,23),valorDe19a23));
        premios.add(new Premio(new com.redhat.saude.cotadorsaude.FaixaEtaria(24,28),valorDe24a28));
        premios.add(new Premio(new com.redhat.saude.cotadorsaude.FaixaEtaria(29,33),valorDe29a33));
        premios.add(new Premio(new com.redhat.saude.cotadorsaude.FaixaEtaria(34,38),valorDe34a38));
        premios.add(new Premio(new com.redhat.saude.cotadorsaude.FaixaEtaria(39,43),valorDe39a43));
        premios.add(new Premio(new com.redhat.saude.cotadorsaude.FaixaEtaria(44,48),valorDe44a48));
        premios.add(new Premio(new com.redhat.saude.cotadorsaude.FaixaEtaria(49,53),valorDe49a53));
        premios.add(new Premio(new com.redhat.saude.cotadorsaude.FaixaEtaria(54,58),valorDe54a58));
        premios.add(new Premio(new com.redhat.saude.cotadorsaude.FaixaEtaria(59,0),valorAPartir59));
    }

	public java.lang.String getNomePlano() {
		return this.nomePlano;
	}

	public void setNomePlano(java.lang.String nomePlano) {
		this.nomePlano = nomePlano;
	}

	public java.lang.Double getValorDe00a18() {
		return this.valorDe00a18;
	}

	public void setValorDe00a18(java.lang.Double valorDe00a18) {
		this.valorDe00a18 = valorDe00a18;
	}

	public java.lang.Double getValorDe19a23() {
		return this.valorDe19a23;
	}

	public void setValorDe19a23(java.lang.Double valorDe19a23) {
		this.valorDe19a23 = valorDe19a23;
	}

	public java.lang.Double getValorDe24a28() {
		return this.valorDe24a28;
	}

	public void setValorDe24a28(java.lang.Double valorDe24a28) {
		this.valorDe24a28 = valorDe24a28;
	}

	public java.lang.Double getValorDe29a33() {
		return this.valorDe29a33;
	}

	public void setValorDe29a33(java.lang.Double valorDe29a33) {
		this.valorDe29a33 = valorDe29a33;
	}

	public java.lang.Double getValorDe34a38() {
		return this.valorDe34a38;
	}

	public void setValorDe34a38(java.lang.Double valorDe34a38) {
		this.valorDe34a38 = valorDe34a38;
	}

	public java.lang.Double getValorDe39a43() {
		return this.valorDe39a43;
	}

	public void setValorDe39a43(java.lang.Double valorDe39a43) {
		this.valorDe39a43 = valorDe39a43;
	}

	public java.lang.Double getValorDe44a48() {
		return this.valorDe44a48;
	}

	public void setValorDe44a48(java.lang.Double valorDe44a48) {
		this.valorDe44a48 = valorDe44a48;
	}

	public java.lang.Double getValorDe49a53() {
		return this.valorDe49a53;
	}

	public void setValorDe49a53(java.lang.Double valorDe49a53) {
		this.valorDe49a53 = valorDe49a53;
	}

	public java.lang.Double getValorDe54a58() {
		return this.valorDe54a58;
	}

	public void setValorDe54a58(java.lang.Double valorDe54a58) {
		this.valorDe54a58 = valorDe54a58;
	}

	public java.lang.Double getValorAPartir59() {
		return this.valorAPartir59;
	}

	public void setValorAPartir59(java.lang.Double valorAPartir59) {
		this.valorAPartir59 = valorAPartir59;
	}

	public java.util.List<com.redhat.saude.cotadorsaude.Premio> getPremios() {
		return this.premios;
	}

	public void setPremios(
			java.util.List<com.redhat.saude.cotadorsaude.Premio> premios) {
		this.premios = premios;
	}

	public ListarPremiosPorPlanoResponse(java.lang.String nomePlano,
			java.lang.Double valorDe00a18, java.lang.Double valorDe19a23,
			java.lang.Double valorDe24a28, java.lang.Double valorDe29a33,
			java.lang.Double valorDe34a38, java.lang.Double valorDe39a43,
			java.lang.Double valorDe44a48, java.lang.Double valorDe49a53,
			java.lang.Double valorDe54a58, java.lang.Double valorAPartir59,
			java.util.List<com.redhat.saude.cotadorsaude.Premio> premios) {
		this.nomePlano = nomePlano;
		this.valorDe00a18 = valorDe00a18;
		this.valorDe19a23 = valorDe19a23;
		this.valorDe24a28 = valorDe24a28;
		this.valorDe29a33 = valorDe29a33;
		this.valorDe34a38 = valorDe34a38;
		this.valorDe39a43 = valorDe39a43;
		this.valorDe44a48 = valorDe44a48;
		this.valorDe49a53 = valorDe49a53;
		this.valorDe54a58 = valorDe54a58;
		this.valorAPartir59 = valorAPartir59;
		this.premios = premios;
	}

}