package com.redhat.saude.cotadorsaude;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Premio implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Faixa Etária")
	private com.redhat.saude.cotadorsaude.FaixaEtaria faixaEtaria;
	@org.kie.api.definition.type.Label(value = "SubTotal")
	private java.lang.Double subTotal;

	public Premio() {
	}

	public com.redhat.saude.cotadorsaude.FaixaEtaria getFaixaEtaria() {
		return this.faixaEtaria;
	}

	public void setFaixaEtaria(
			com.redhat.saude.cotadorsaude.FaixaEtaria faixaEtaria) {
		this.faixaEtaria = faixaEtaria;
	}

	public java.lang.Double getSubTotal() {
		return this.subTotal;
	}

	public void setSubTotal(java.lang.Double subTotal) {
		this.subTotal = subTotal;
	}

	public Premio(com.redhat.saude.cotadorsaude.FaixaEtaria faixaEtaria,
			java.lang.Double subTotal) {
		this.faixaEtaria = faixaEtaria;
		this.subTotal = subTotal;
	}

}