package com.redhat.saude.cotadorsaude;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TabelaPlanos implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("REFERÊNCIA")
	private java.lang.Double referencia;
	@org.kie.api.definition.type.Label("Direto ABC II enf")
	private java.lang.Double diretoabciienf;
	@org.kie.api.definition.type.Label("Direto ABC II apto")
	private java.lang.Double diretoabciiapto;
	@org.kie.api.definition.type.Label("EXATO apto")
	private java.lang.Double exatoenf;
	@org.kie.api.definition.type.Label("EXATO apto")
	private java.lang.Double exatoapto;
	@org.kie.api.definition.type.Label("CLÁSSICO enf")
	private java.lang.Double classicoenf;
	@org.kie.api.definition.type.Label("CLÁSSICO apto")
	private java.lang.Double classicoapto;
	@org.kie.api.definition.type.Label("ESPECIAL 100 R1")
	private java.lang.Double especial100r1;
	@org.kie.api.definition.type.Label("ESPECIAL 100 R2")
	private java.lang.Double especial100r2;
	@org.kie.api.definition.type.Label("ESPECIAL 100 R3")
	private java.lang.Double especial100r3;
	@org.kie.api.definition.type.Label("EXECUTIVO R1")
	private java.lang.Double executivor1;
	@org.kie.api.definition.type.Label("EXECUTIVO R2")
	private java.lang.Double executivor2;
	@org.kie.api.definition.type.Label("EXECUTIVO R3")
	private java.lang.Double executivor3;
	@org.kie.api.definition.type.Label("PRESTIGE")
	private java.lang.Double prestige;

	@org.kie.api.definition.type.Label("Produto")
	private java.lang.Integer produto;

	@org.kie.api.definition.type.Label("Código da região")
	private java.lang.Integer regiao;

	@org.kie.api.definition.type.Label("Faixa Inicial")
	private java.lang.Integer faixaInicial;

	@org.kie.api.definition.type.Label("Faixa Final")
	private java.lang.Integer faixaFinal;

	@org.kie.api.definition.type.Label(value = "Vigencia Inicial")
	private java.time.LocalDate vigenciaInicial;

	@org.kie.api.definition.type.Label(value = "Vigência Final")
	private java.time.LocalDate vigenciaFinal;

	@org.kie.api.definition.type.Label(value = "Data da referência da cotação")
	private java.time.LocalDate dataCotacao;

	public TabelaPlanos() {
	}

	public Double retornarValorPlano(int codPlano) {
		switch (codPlano) {
			case 1 :
				return referencia;
			case 2 :
				return diretoabciienf;
			case 3 :
				return diretoabciiapto;
			case 4 :
				return exatoenf;
			case 5 :
				return exatoapto;
			case 6 :
				return classicoenf;
			case 7 :
				return classicoapto;
			case 8 :
				return especial100r1;
			case 9 :
				return especial100r2;
			case 10 :
				return especial100r3;
			case 11 :
				return executivor1;
			case 12 :
				return executivor2;
			case 13 :
				return executivor3;
			case 14 :
				return prestige;
			default :
				return 0.00;
		}
	}

	public com.redhat.saude.cotadorsaude.responses.TabelaPrecoResponse configureResponse() {
		com.redhat.saude.cotadorsaude.responses.TabelaPrecoResponse response = new com.redhat.saude.cotadorsaude.responses.TabelaPrecoResponse();
		response.setFaixaEtaria(new com.redhat.saude.cotadorsaude.FaixaEtaria(
				faixaInicial, faixaFinal));
		response.getPlanos().add(
				new com.redhat.saude.cotadorsaude.Plano(1, "REFERÊNCIA",
						referencia));
		response.getPlanos().add(
				new com.redhat.saude.cotadorsaude.Plano(2, "Direto ABC II enf",
						diretoabciienf));
		response.getPlanos().add(
				new com.redhat.saude.cotadorsaude.Plano(3,
						"Direto ABC II apto", diretoabciiapto));
		response.getPlanos().add(
				new com.redhat.saude.cotadorsaude.Plano(4, "EXATO apto",
						exatoenf));
		response.getPlanos().add(
				new com.redhat.saude.cotadorsaude.Plano(5, "EXATO apto",
						exatoapto));
		response.getPlanos().add(
				new com.redhat.saude.cotadorsaude.Plano(6, "CLÁSSICO enf",
						classicoenf));
		response.getPlanos().add(
				new com.redhat.saude.cotadorsaude.Plano(7, "CLÁSSICO apto",
						classicoapto));
		response.getPlanos().add(
				new com.redhat.saude.cotadorsaude.Plano(8, "ESPECIAL 100 R1",
						especial100r1));
		response.getPlanos().add(
				new com.redhat.saude.cotadorsaude.Plano(9, "ESPECIAL 100 R2",
						especial100r2));
		response.getPlanos().add(
				new com.redhat.saude.cotadorsaude.Plano(10, "ESPECIAL 100 R3",
						especial100r3));
		response.getPlanos().add(
				new com.redhat.saude.cotadorsaude.Plano(11, "EXECUTIVO R1",
						executivor1));
		response.getPlanos().add(
				new com.redhat.saude.cotadorsaude.Plano(12, "EXECUTIVO R2",
						executivor2));
		response.getPlanos().add(
				new com.redhat.saude.cotadorsaude.Plano(13, "EXECUTIVO R3",
						executivor3));
		response.getPlanos().add(
				new com.redhat.saude.cotadorsaude.Plano(14, "PRESTIGE",
						prestige));

		return response;
	}

	public java.lang.Double getReferencia() {
		return this.referencia;
	}

	public void setReferencia(java.lang.Double referencia) {
		this.referencia = referencia;
	}

	public java.lang.Double getDiretoabciienf() {
		return this.diretoabciienf;
	}

	public void setDiretoabciienf(java.lang.Double diretoabciienf) {
		this.diretoabciienf = diretoabciienf;
	}

	public java.lang.Double getDiretoabciiapto() {
		return this.diretoabciiapto;
	}

	public void setDiretoabciiapto(java.lang.Double diretoabciiapto) {
		this.diretoabciiapto = diretoabciiapto;
	}

	public java.lang.Double getExatoenf() {
		return this.exatoenf;
	}

	public void setExatoenf(java.lang.Double exatoenf) {
		this.exatoenf = exatoenf;
	}

	public java.lang.Double getExatoapto() {
		return this.exatoapto;
	}

	public void setExatoapto(java.lang.Double exatoapto) {
		this.exatoapto = exatoapto;
	}

	public java.lang.Double getClassicoenf() {
		return this.classicoenf;
	}

	public void setClassicoenf(java.lang.Double classicoenf) {
		this.classicoenf = classicoenf;
	}

	public java.lang.Double getClassicoapto() {
		return this.classicoapto;
	}

	public void setClassicoapto(java.lang.Double classicoapto) {
		this.classicoapto = classicoapto;
	}

	public java.lang.Double getEspecial100r1() {
		return this.especial100r1;
	}

	public void setEspecial100r1(java.lang.Double especial100r1) {
		this.especial100r1 = especial100r1;
	}

	public java.lang.Double getEspecial100r2() {
		return this.especial100r2;
	}

	public void setEspecial100r2(java.lang.Double especial100r2) {
		this.especial100r2 = especial100r2;
	}

	public java.lang.Double getEspecial100r3() {
		return this.especial100r3;
	}

	public void setEspecial100r3(java.lang.Double especial100r3) {
		this.especial100r3 = especial100r3;
	}

	public java.lang.Double getExecutivor1() {
		return this.executivor1;
	}

	public void setExecutivor1(java.lang.Double executivor1) {
		this.executivor1 = executivor1;
	}

	public java.lang.Double getExecutivor2() {
		return this.executivor2;
	}

	public void setExecutivor2(java.lang.Double executivor2) {
		this.executivor2 = executivor2;
	}

	public java.lang.Double getExecutivor3() {
		return this.executivor3;
	}

	public void setExecutivor3(java.lang.Double executivor3) {
		this.executivor3 = executivor3;
	}

	public java.lang.Double getPrestige() {
		return this.prestige;
	}

	public void setPrestige(java.lang.Double prestige) {
		this.prestige = prestige;
	}

	public java.lang.Integer getProduto() {
		return this.produto;
	}

	public void setProduto(java.lang.Integer produto) {
		this.produto = produto;
	}

	public java.lang.Integer getRegiao() {
		return this.regiao;
	}

	public void setRegiao(java.lang.Integer regiao) {
		this.regiao = regiao;
	}

	public java.lang.Integer getFaixaInicial() {
		return this.faixaInicial;
	}

	public void setFaixaInicial(java.lang.Integer faixaInicial) {
		this.faixaInicial = faixaInicial;
	}

	public java.lang.Integer getFaixaFinal() {
		return this.faixaFinal;
	}

	public void setFaixaFinal(java.lang.Integer faixaFinal) {
		this.faixaFinal = faixaFinal;
	}

	public java.time.LocalDate getVigenciaInicial() {
		return this.vigenciaInicial;
	}

	public void setVigenciaInicial(java.time.LocalDate vigenciaInicial) {
		this.vigenciaInicial = vigenciaInicial;
	}

	public java.time.LocalDate getVigenciaFinal() {
		return this.vigenciaFinal;
	}

	public void setVigenciaFinal(java.time.LocalDate vigenciaFinal) {
		this.vigenciaFinal = vigenciaFinal;
	}

	public java.time.LocalDate getDataCotacao() {
		return this.dataCotacao;
	}

	public void setDataCotacao(java.time.LocalDate dataCotacao) {
		this.dataCotacao = dataCotacao;
	}

	public TabelaPlanos(java.lang.Double referencia,
			java.lang.Double diretoabciienf, java.lang.Double diretoabciiapto,
			java.lang.Double exatoenf, java.lang.Double exatoapto,
			java.lang.Double classicoenf, java.lang.Double classicoapto,
			java.lang.Double especial100r1, java.lang.Double especial100r2,
			java.lang.Double especial100r3, java.lang.Double executivor1,
			java.lang.Double executivor2, java.lang.Double executivor3,
			java.lang.Double prestige, java.lang.Integer produto,
			java.lang.Integer regiao, java.lang.Integer faixaInicial,
			java.lang.Integer faixaFinal, java.time.LocalDate vigenciaInicial,
			java.time.LocalDate vigenciaFinal, java.time.LocalDate dataCotacao) {
		this.referencia = referencia;
		this.diretoabciienf = diretoabciienf;
		this.diretoabciiapto = diretoabciiapto;
		this.exatoenf = exatoenf;
		this.exatoapto = exatoapto;
		this.classicoenf = classicoenf;
		this.classicoapto = classicoapto;
		this.especial100r1 = especial100r1;
		this.especial100r2 = especial100r2;
		this.especial100r3 = especial100r3;
		this.executivor1 = executivor1;
		this.executivor2 = executivor2;
		this.executivor3 = executivor3;
		this.prestige = prestige;
		this.produto = produto;
		this.regiao = regiao;
		this.faixaInicial = faixaInicial;
		this.faixaFinal = faixaFinal;
		this.vigenciaInicial = vigenciaInicial;
		this.vigenciaFinal = vigenciaFinal;
		this.dataCotacao = dataCotacao;
	}

}